### ISSUE TITLE
Export scenes

### ISSUE THREAD

**Issue by szamq** [reattiva/Urho3D-Blender#15]
Would be great if we could export whole scenes with saved: position, rotations and scales for each object. I know thats possible with merge checkbox and then importing that in urho, but then you have all scene merged as one model and it's impossible to turn some parameters like lightmask for certain parts of whole model. On the other hand, I can export without merge checkbox and I have all parts separately which is really cool, but then additional work is needed in urho, like creating nodes for each geometry(each tree, little bush, all rocks).

Btw. Thanks for great exporter, I see lot of improvements here since the first release and it all just works!

**Comment by gabdab** [comment]
I sketched a basic scene exporter for blender (v.2.76 has broken .fbx exporter , I use 2.73 so far) .
You can get code here : http://urho3d.prophpbb.com/post7585.html
Just paste it in text window inside blender and 'run script' .

**Comment by reattiva** [comment]
It can prove useful, thanks.

**Comment by gabdab** [comment]
Your welcome .
