### ISSUE TITLE
Can not install on blender 2.70 & blender 2.72b

### ISSUE THREAD

**Issue by Syjgin** [reattiva/Urho3D-Blender#41]
I have downloaded archive, repacked io_mesh_urho into archive and open via "Blender User Preferences" menu. After this, there are no Urho3D plugin to activate in list, but no error message too. Here is a program output:

connect failed: No such file or directory
found bundled python: /home/syjgin/blender-2.72b-linux-glibc211-x86_64/2.72/python
Modules Installed from '/home/syjgin/Urho3D-Blender-master/io_mesh_urho.zip' into '/home/syjgin/.config/blender/2.72/
![5](https://cloud.githubusercontent.com/assets/3268587/5625145/debbdd22-9585-11e4-8ff6-dee3a5b2291e.png)
scripts/addons' ()

On the "/home/syjgin/.config/blender/2.72/scripts/addons" folder I found the copy of  io_mesh_urho.zip and nothing else.

**Comment by dervus** [comment]
As I know "Install from file" button is about standalone .py files only. In case of urho3d-blender you should manually extract the archive into ~/.config/blender/2.72/scripts/addons

**Comment by Syjgin** [comment]
thank you, now I can enable plugin, but there are no corresponding option in "Export" menu
![6](https://cloud.githubusercontent.com/assets/3268587/5658303/a1dcf2e2-9710-11e4-87ff-3d4e5a7051fb.png)

**Comment by reattiva** [comment]
Hello Syjgin, please read the guide carefully:
https://github.com/reattiva/Urho3D-Blender/blob/master/guide.txt
