### ISSUE TITLE
Exporting Custom Normals

### ISSUE THREAD

**Issue by hdunderscore** [reattiva/Urho3D-Blender#45]
Hey,

Blender now has a new feature in master that lets you manipulate the normals via two modifiers (Data Transfer and Normal Edit). The normals that these modifiers produce don't seem to be exported with Urho3D-Blender exporter.

Thanks

**Comment by reattiva** [comment]
Not much info I guess... However I've looked around and found [this](https://mont29.wordpress.com/2014/11/10/data-transfer-first-test-build/) for the first modifier. If it is a modifier then using "Apply modifiers" should do the trick. 
I'll wait for 2.74 to be released, but I can assure you I have no idea how it works.
If you want to give it a try, [this](https://github.com/reattiva/Urho3D-Blender/blob/master/io_mesh_urho/decompose.py#L1670) is where the vertex normal is loaded.

**Comment by JTippetts** [comment]
2.74 is out, and it doesn't look to me like Apply Modifiers is actually working for this. I'm no expert, but I wonder if it has to do with the fact that modifiers are applied at line 1444 ( https://github.com/reattiva/Urho3D-Blender/blob/master/io_mesh_urho/decompose.py#L1444 ) then at line 1875 ( https://github.com/reattiva/Urho3D-Blender/blob/master/io_mesh_urho/decompose.py#L1875 ) the mesh is updated to recalculate normals, probably undoing the normals from the modifier. Of course, commenting out the mesh update doesn't seem to do the trick, either, so what do I know?

**Comment by reattiva** [comment]
Try this branch:
https://github.com/reattiva/Urho3D-Blender/tree/split_normals

**Comment by hdunderscore** [comment]
Hey just letting you know I am still interested in this-- I just haven't had a chance to test this new solution in depth. I'll be looking at it again in a few weeks. Thanks for the work !

**Comment by hdunderscore** [comment]
It's been a while, but from my tests this appears to work now ! Thanks a lot :D

**Comment by hdunderscore** [comment]
Great to see that branch merged, thanks again !
