### ISSUE TITLE
Bone bounding box based on bone length

### ISSUE THREAD

**Issue by Mike3D** [reattiva/Urho3D-Blender#56]
Hi reattiva,

Currently bones bounding box is computed by checking neighbour weighted vertices.
This gives good results, but creates overlapping bounding boxes, which makes life not easy when procedurally creating ragdolls or inverse kinematics setups.
To overcome this issue, I'm using a Skeleton export option that allows to compute bones bounding box based on their length. That way the bounding box doesn't grow beyond head and tail.

If you are OK to add this option I can submit a PR.

**Comment by reattiva** [comment]
Ok, sounds good.

**Comment by Mike3D** [comment]
Many thanks  :thumbsup:
