### ISSUE TITLE
Error when exporting raw blender 

### ISSUE THREAD

**Issue by greatPHPer** [reattiva/Urho3D-Blender#68]
When I go to blender and export the cube, I get the following error
![urho3derror](https://cloud.githubusercontent.com/assets/14175476/26759101/eaf61750-4911-11e7-88c6-5c30bf4f036a.png)
I don't know to solve the problem
Thanks in advance

**Comment by reattiva** [comment]
What version of Blender are you using?
It must be a 2.70 al least.

**Comment by greatPHPer** [comment]
thanks very much. It's working now! I have downloaded 2.70a now @reattiva <3
