### ISSUE TITLE
Exported MDL not working in android

### ISSUE THREAD

**Issue by greatPHPer** [reattiva/Urho3D-Blender#69]
Hi,
I am new to Urho3D . I'm using Xamarin for Urho3D in Visual studio 2015.
I imported a stone .3ds file into blender version 2.70a, and exported it to mdl file.
When I used it in my Xamarin application using 
    modelObject.Model = ResourceCache.GetModel("Models/Cube.mdl");
the exported mdl file doesn't load and the App exits.
However it works for basic blender cube exported to MDL
I even tried it with an .obj file and an .mtl file.
This is my .3ds file
http://s000.tinyupload.com/index.php?file_id=09438689685458714793
Visual Studio version: 14.0.25431.01 Update 3
Xamarin version: 4.2.0.703 
Blender version: 2.70a

Thanks

**Comment by Mike3D** [comment]
What happens when you 'load' your model in the Editor or in one of the samples ?

**Comment by greatPHPer** [comment]
Hi,
Sorry for the delay,
when I go to File -> Import Model... -> Rock1.mdl, it shows error 
ERROR: Failed to execute AssetImporter to import model
Is the problem in my .3ds file? It is a rock model and I downloaded it from the web. Is there an Urho3D .mdl file for a rock?
Thanks in advance

**Comment by Mike3D** [comment]
As long as you can import your model in Blender, all is well.
Try to use your Rock1.mdl in a sample project run from the Player (for example add your modelObject.Model = ResourceCache.GetModel("Models/Cube.mdl"); to 04_StaticScene) and check what's going on.

**Comment by greatPHPer** [comment]
Hi,
I am unable to run the script in urho3d player
I went to File -> Run Script ... -> 04_StaticScene
It shows error in console
[Wed Jun 28 19:56:49 2017] WARNING: Localization::Get("Execute Script") not found translation, language="en"
[Wed Jun 28 19:57:52 2017] WARNING: Localization::Get("Create Replicated Node") not found translation, language="en"
[Wed Jun 28 19:57:52 2017] WARNING: Localization::Get("Create Local Node") not found translation, language="en"
[Wed Jun 28 19:58:17 2017] WARNING: Localization::Get("Execute Script") not found translation, language="en"
[Wed Jun 28 19:58:54 2017] WARNING: Localization::Get("Execute Script") not found translation, language="en"
[Wed Jun 28 19:59:15 2017] WARNING: Localization::Get("Execute Script") not found translation, language="en"
[Wed Jun 28 19:59:16 2017] WARNING: Localization::Get("Execute Script") not found translation, language="en"
[Wed Jun 28 19:59:31 2017] WARNING: Localization::Get("Execute Script") not found translation, language="en"
[Wed Jun 28 20:01:11 2017] INFO: Device lost
[Wed Jun 28 20:03:04 2017] INFO: Device lost
[Wed Jun 28 20:04:29 2017] INFO: Device lost
[Wed Jun 28 20:04:36 2017] INFO: Device lost
[Wed Jun 28 20:04:50 2017] ERROR: :7,1 Expected expression value
[Wed Jun 28 20:04:50 2017] ERROR: :7,1 Instead found '<unrecognized token>'
[Wed Jun 28 20:04:50 2017] ERROR: :30,6 Expected ';'
[Wed Jun 28 20:04:50 2017] ERROR: :30,6 Instead found identifier 'CreateScene'
[Wed Jun 28 20:04:50 2017] ERROR: :84,6 Expected ';'
[Wed Jun 28 20:04:50 2017] ERROR: :84,6 Instead found identifier 'CreateInstructions'
[Wed Jun 28 20:04:50 2017] ERROR: :97,6 Expected ';'
[Wed Jun 28 20:04:50 2017] ERROR: :97,6 Instead found identifier 'SetupViewport'
[Wed Jun 28 20:04:50 2017] ERROR: :106,6 Expected ';'
[Wed Jun 28 20:04:50 2017] ERROR: :106,6 Instead found identifier 'MoveCamera'
[Wed Jun 28 20:04:50 2017] ERROR: :138,6 Expected ';'
[Wed Jun 28 20:04:50 2017] ERROR: :138,6 Instead found identifier 'SubscribeToEvents'
[Wed Jun 28 20:04:50 2017] ERROR: :144,6 Expected ';'
[Wed Jun 28 20:04:50 2017] ERROR: :144,6 Instead found identifier 'HandleUpdate'

**Comment by greatPHPer** [comment]
My model file is opening in the player when I drag it to the scene, but I am unable to execute any action scripts , maybe because I am using Windows OS?
when I go to File -> Run script... -> 04_StaticScene.as , it gives javascript errors (like "expected ';' instead found identifier 'CreateScene'

**Comment by Mike3D** [comment]
Do errors occur with unmodified script ?

**Comment by greatPHPer** [comment]
Yes, I actually used Visual studio to compile Urho3D , maybe that is a reason. :(
When I go to File -> Run Script... -> 04_StaticScene.as
I get the following error
![urho3derror2](https://user-images.githubusercontent.com/14175476/27763508-7722d10a-5ea2-11e7-807f-e68563b4f9d1.png)

**Comment by Mike3D** [comment]
Can you post the first 10 lines of the script

**Comment by greatPHPer** [comment]
`// Static 3D scene example.
// This sample demonstrates:
//     - Creating a 3D scene with static content
//     - Displaying the scene using the Renderer subsystem
//     - Handling keyboard and mouse input to move a freelook camera

#include "Scripts/Utilities/Sample.as"

void Start()
{
    // Execute the common startup for samples
    SampleStart();

    // Create the scene content
    CreateScene();

    // Create the UI content
    CreateInstructions();

    // Setup the viewport for displaying the scene
    SetupViewport();

    // Set the mouse mode to use in the sample
    SampleInitMouseMode(MM_RELATIVE);

    // Hook up to the frame update events
    SubscribeToEvents();
}
`

**Comment by reattiva** [comment]
Hello, I've tried to export the your 3ds file and there were no errors when loading it in the editor.
Notes: 
In the editor you don't need to use "file -> import" to load a mdl file, you need to add a node and a static model to the node. 
The "expected ;" problem could be caused by the file "Sample.as" you have included.

**Comment by greatPHPer** [comment]
I am using Urho3D-blender addon for creating android Xamarin project. Only basic cube is working on real android. I tried to scale the other models to smaller size, and they  didn't load in real android. Does this issue belong to this section?

**Comment by Mike3D** [comment]
I'm not familiar at all with Xamarin. Are you sure that AngelScript is supported ?

**Comment by reattiva** [comment]
Neither am I. The problem seems to be in your Xamarin installation, better ask help at their forum.
