### ISSUE TITLE
Export Urho Prefabs to include Position

### ISSUE THREAD

**Issue by stark7** [reattiva/Urho3D-Blender#74]
Hello @reattiva and thanks a bunch for this plugin - it rocks!

My use case is that I am exporting a prefab in which I want each model to use local origin and for that to work I need the One Collective option to include a relative position to the parent empty that is the world position in the blender scene.

Is there maybe another way to achieve this without having to modify the exporter code?

Edit: I took the scenic route from the trasf option to where it is in the plugin - it's under Scene Prefab check checkbox.

**Comment by reattiva** [comment]
Yes, you need to set the Origin option to "Local" then you set "Export Urho Prefabs" -> "Scene Prefab" -> "Transform objects". (correct me if I'm wrong)
This is an incomplete feature and it only works with Front View = Back.
Mike3D was working to fix it and improve the animations exporting performance. 
A better documentation could help too.
