### ISSUE TITLE
Vertex color bleeding

### ISSUE THREAD

**Issue by QBkGames** [reattiva/Urho3D-Blender#79]
If you have adjacent faces that have different vertex colors, the colors would merge/bleed when exported to Urho3D. So faces have to be separated by color as well.

![smudged colors](https://user-images.githubusercontent.com/30278394/35774604-741291ae-09c8-11e8-8981-17dfa8439e26.jpg)

I've already got a fix, but I don't seem to be able to create a Pull request.
The file 'decompose.py' should be changed as follows:

    # used by the function index() of lists
    def __eq__(self, other):
        # TODO: can we do without weights?
        # TODO: compare floats with a epsilon margin?
        #return (self.__dict__ == other.__dict__)
        return (self.pos == other.pos and 
                self.normal == other.normal and 
                self.uv == other.uv and
		self.color == other.color)

    def isEqual(self, other):
        # TODO: compare floats with a epsilon margin?
        return self == other
                
    def __hash__(self):
        hashValue = 0
        if self.pos:
            hashValue ^= hash(self.pos.x) ^ hash(self.pos.y) ^ hash(self.pos.z)
        if self.normal:
            hashValue ^= hash(self.normal.x) ^ hash(self.normal.y) ^ hash(self.normal.z)
        if self.uv:
            hashValue ^= hash(self.uv.x) ^ hash(self.uv.y)
        if self.color:
            hashValue ^= hash(self.color[0]) ^ hash(self.color[1]) ^ hash(self.color[2]) ^ hash(self.color[3])
        return hashValue

**Comment by QBkGames** [comment]
I've finally figured out (with some assistance) how to do pull request, so I've submitted one for this issue.
#81

**Comment by reattiva** [comment]
Ok, merged.
