### ISSUE TITLE
Trying to export LOD objects will fail if using different materials

### ISSUE THREAD

**Issue by solorvox** [reattiva/Urho3D-Blender#86]
If you try to export LOD objects with different materials (and without exporting materials selected), the export cannot match objects together.  It does say it finds _LOD000 but they don't link to other objects in the group.

**Repo**: 
1) Create three objects in blender, name _LODXXX.  
2) Add a unique material to each one and try to export.
Bug: First LOD of object MyObj Geo... have 0.0 distance (found 100.000)

**Workaround**:  Remove materials from ALL objects and export.

Having lower resolution materials/or faster techniques, would be nice for each LOD level.

**Comment by reattiva** [comment]
I think this is probably correct. If you change material you are adding a new geometry and LOD levels are inside a geometry, so you cannot have different materials for different LODs.
What you can do is use the same material for all LODs, then inside that material you can specify a technique per LOD distance.
This exporter is not able to do this job for you.

**Comment by Modanung** [comment]
Seems like this could be closed?
