### ISSUE TITLE
Can't export shape keys in blender 2.79

### ISSUE THREAD

**Issue by Shtrompel** [reattiva/Urho3D-Blender#91]
When i'm trying to export morphs (shape keys) from blender, the report that's showing up is saying that the key is empty. Even though the key is enabled and working fine.

![alt text](https://i.imgur.com/U6M5Bzx.png)

I tried with blender 2.70 and play with the settings but I got the same results.

**Comment by reattiva** [comment]
Hello, try enabling "Apply modifiers".

**Comment by Shtrompel** [comment]
Apply modifiers does fix the problem. I didn't know that the shape keys are considered to be modifiers.
